spring:
  application:
    name: spring-security
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            issuer-uri: https://gitlab.com
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
        registration:
            gitlab:
                client-id: f6447fd0bda20db45ab616b5d4f486a5f0e92617c607f7660e5282dc39257bc1
                client-secret: gloas-0ef1fc0354788b885ae09ef401f19ef2d0e772f37d44d4505933f9c9a74ee94f
                scope: openid
                redirect-uri: "http://localhost:8082/login/oauth2/code/gitlab"
                authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: https://gitlab.com
          jwk-set-uri: https://gitlab.com/oauth/discovery/keys

server:
  port: 8082

